<?php

namespace AppBundle\Repository;

/**
 * OntvangenGoederenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OntvangstmeldingRepository extends \Doctrine\ORM\EntityRepository
{
}
