# # app/config/security.yml
# security:
#     encoders:
#         AppBundle\Entity\Gb:
#             algorithm: bcrypt

#     # ...

#     providers:
#         our_db_provider:
#             entity:
#                 class: AppBundle:Gebruiker
#                 property: username
#                 # if you're using multiple entity managers
#                 # manager_name: customer

#     firewalls:
#         main:
#             pattern:    ^/
#             http_basic: ~
#             provider: our_db_provider

#     # ...
