# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        in_memory: 
            memory: 
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_INKOPER'

                    magazijnmeester:
                        password: magazijnmeester
                        roles: 'ROLE_MAGAZIJNMEESTER'

                    # testgebruiker:
                    #     password: test
                    #     roles: 'ROLE_GEBRUIKER'

   # access_control:
    #    - { path: '^/artikel/nieuw', roles: [ROLE_INKOPER] }
     #   - { path: '^/artikel/wijzig/{artikelnummer}', roles: [ROLE_INKOPER] }
      #  - { path: '^/artikel/verwijder/{artikelnummer}', roles: [ROLE_INKOPER] }
       # - { path: '^/search/artikel', roles: [ROLE_INKOPER] }
        #- { path: '^/bestelorder/nieuw', roles: [ROLE_MAGAZIJNMEESTER] }
        #- { path: '^/bestelorder/wijzig/{bestelordernummer}', roles: [ROLE_MAGAZIJNMEESTER] }
        #- { path: '^/bestelorder/verwijder/{bestelordernummer}', roles: [ROLE_MAGAZIJNMEESTERROLE_MAGAZIJNMEESTER] }
        #- { path: '^/bestelorderoverzicht', roles: [ROLE_MAGAZIJNMEESTER] }
        #- { path: '^/ontvangengoederen/nieuw', roles: [ROLE_MAGAZIJNMEESTER] }
        #- { path: '^/ontvangengoederen/wijzig/{ontvangstnummer}', roles: [ROLE_MAGAZIJNMEESTER] }
        #- { path: '^/ontvangengoederen/verwijder/{ontvangstnummer}', roles: [ROLE_MAGAZIJNMEESTERROLE_MAGAZIJNMEESTER] }
        #- { path: '^/ontvangengoederen/alle', roles: [ROLE_MAGAZIJNMEESTER] }
        #- { path: '^/nietontvangengoederen/alle', roles: [ROLE_MAGAZIJNMEESTER] }
         #- { path: '^/*', roles: [ROLE_MAGAZIJNMEESTER] }
    

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            logout:
                path:   /logout
                target: /home
