# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
      #in_memory:
      #      memory:
      #          users:
      #                marice:
      #                    password: user
      #                    roles: 'ROLE_USER'
      #                admin:
      #                    password: admin
      #                    roles: 'ROLE_ADMIN'
      our_db_provider:
          entity:
                class: AppBundle:User
                property: username

    encoders:
        AppBundle\Entity\User: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          provider: db_provider
          security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            form_login:
                login_path: login
                check_path: login

    access_control:
        # Inkoper path
        - { path: ^/INKOPER/*, roles: ROLE_INKOPER }

        # Verkoper path
        - { path: ^/VERKOPER/*, roles: ROLE_VERKOPER }

        # Magazijnmeester path
        - { path: ^/MAGAZIJNMEESTER/*, roles: ROLE_MAGAZIJNMEESTER }


        # Admin path
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/register, roles: ROLE_ADMIN }

        # Anonymous path
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

