<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5vshqmp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5vshqmp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5vshqmp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5vshqmp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5vshqmp\appDevDebugProjectContainer(array(
    'container.build_hash' => '5vshqmp',
    'container.build_id' => 'cbd7fdac',
    'container.build_time' => 1527778633,
), __DIR__.\DIRECTORY_SEPARATOR.'Container5vshqmp');
