<?php

namespace AppBundle\Repository;

/**
 * BestellenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestellenRepository extends \Doctrine\ORM\EntityRepository
{
}